# Generated by Django 5.2 on 2025-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('icerik', models.TextField()),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
