# Generated by Django 5.2 on 2025-04-14 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('durum', models.CharField(choices=[('bos', 'Boş'), ('rezerve', 'Rezerve'), ('iptal', 'İptal Edildi')], default='bos', max_length=10)),
                ('ogrenci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aldigim_etutler', to=settings.AUTH_USER_MODEL)),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdigim_etutler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Makale',
        ),
    ]
